# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require "./commit_message"
require "./report_func"

ENV["app-id-stg"] = "1:944710506543:ios:8bf1c715021afd9cad4eda"
ENV["app-id-dev"] = "1:944710506543:ios:c9d26b30f06f3eefad4eda"
ENV["app-id-prod"] = "1:944710506543:ios:8de4e07e31244461ad4eda"
ENV["group"] = "only-me"

default_platform(:ios)

platform :ios do

  before_all do |lane,options|
    puts Dir.pwd
    cocoapods(
      clean_install: true,
      podfile: "./Podfile"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

 # crashLytics
 desc "adhoc_firebase_bitrise"
 lane :adhoc_firebase_bitrise do |options|
#    say ["crashLytics"]


    match(git_url: "git@github.com:indival-inc/apple_related.git",
	      type: "adhoc",readonly: true,username: "dev-office@indival.co.jp",
        app_identifier: "jp.heal.sounds.stg")
	  gym(
	    export_method: "ad-hoc",
      verbose: true,
      clean: true,
      scheme: 'Runner',
      output_directory: "/Users/vagrant/deploy",
      configuration: 'Release-Staging',
    )
    firebase_app_distribution(
        app: ENV["app-id-stg"] ,
        groups: ENV['group'],
        release_notes: $publish_message,
        firebase_cli_path:  "/usr/local/bin/firebase" # for pipeline
    )
  end
  desc "adhoc_firebase_local"
  lane :adhoc_firebase_local do |options|
#    say ["crashLytics"]
	  gym(
	    export_method: "ad-hoc",
      verbose: true,
      clean: true,
      scheme: 'Runner',
      configuration: 'Release-StagingLocal',
      output_directory: "../fastlaneBuild", # Destination directory. Defaults to current directory.
      output_name: 'StagingSound.ipa' # specify the name of the .ipa file to generate (including file extension)
    )
    firebase_app_distribution(
        ipa_path: '../fastlaneBuild/StagingSound.ipa',
        app: ENV["app-id-stg"] ,
        groups: ENV['group'],
        release_notes: $publish_message,
        firebase_cli_path:  "/usr/local/bin/firebase" # for pipeline
    )
  end

  desc "beta_testflight"
  lane :beta_testflight do |options|
#    say ["crashLytics"]

	  gym(
	    export_method: "app-store",
      verbose: true,
      clean: true,
      scheme: 'Runner',
      configuration: 'Release-Production',
      output_directory: "../fastlaneBuild", # Destination directory. Defaults to current directory.
      output_name: 'ProdYumex.ipa' # specify the name of the .ipa file to generate (including file extension)
    )
    pilot(
      app_platform: "ios",
      team_id: "B97D6M4DM4",
      app_identifier: "jp.yumexnet.app",
		  skip_waiting_for_build_processing:true
	  )
  end
end