# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require "./commit_message"

default_platform(:android)

ENV["group"] = "sound"
ENV["firebase_cli_path"] = "/usr/local/bin/firebase"
ENV["app-id-stg"] = "1:944710506543:android:0754f68602240c6dad4eda"
ENV["app-id-dev"] = "1:944710506543:android:5d866f8cc22e2b15ad4eda"
ENV["app-id-prod"] = "1:944710506543:android:753096b743d4e486ad4eda"

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

   # use like this `fastlane distribute group:only-me`
   desc "Submit a new beta build to Firebase App Distribution"
   lane :upload_debug_dev do |options|
        build_android_app(
           task: "assemble",
           flavor: "development",
           build_type: "debug"
        )

        firebase_app_distribution(
           app: ENV["app-id-dev"],
           groups: ENV["group"],
           release_notes: $publish_message,
           firebase_cli_path:  ENV["firebase_cli_path"] # for pipeline
        )
   end

   # use like this `fastlane distribute group:only-me`
   desc "Submit a new beta build to Firebase App Distribution"
   lane :upload_release_stg do |options|
        build_android_app(
          task: "assemble",
          flavor: "staging",
          build_type: "release",
          properties: {
            "android.injected.signing.store.file" => ENV["keystorepath"],
            "android.injected.signing.store.password" => ENV["release_build_password"],
            "android.injected.signing.key.alias" => "key0",
            "android.injected.signing.key.password" => ENV["release_build_password"],
          }
        )
        firebase_app_distribution(
           app: ENV["app-id-stg"],
           groups: ENV["group"],
           release_notes: $publish_message,
           apk_path: "../build/app/outputs/flutter-apk/app-staging-release.apk",
           firebase_cli_path:  ENV["firebase_cli_path"] # for pipeline
        )
   end

   desc "Submit a new beta build to Firebase App Distribution"
   lane :make_release_build do |options|
       if options[:group]
         build_android_app(
           task: "bundle",
           flavor: options[:flavor],
           build_type: options[:build_type],
           properties: {
             "android.injected.signing.store.file" => Dir.pwd + options[:path],
             "android.injected.signing.store.password" => "sound20201219",
             "android.injected.signing.key.alias" => "key0",
             "android.injected.signing.key.password" => "sound20201219",
           }
         )
       else
         UI.user_error!("Missing group name!")
       end
   end
end
